# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import mt5_pb2 as mt5__pb2


class MT5IngressServiceStub(object):
    """MT5IngressService is the agent->broker contract.
    The MT5 agent (Python) calls this service to push data to the broker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/mt5.v1.MT5IngressService/Connect',
                request_serializer=mt5__pb2.AgentMessage.SerializeToString,
                response_deserializer=mt5__pb2.BrokerMessage.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/mt5.v1.MT5IngressService/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=mt5__pb2.ConnectionStatus.FromString,
                )


class MT5IngressServiceServicer(object):
    """MT5IngressService is the agent->broker contract.
    The MT5 agent (Python) calls this service to push data to the broker.
    """

    def Connect(self, request_iterator, context):
        """Connect opens long-lived bi-directional stream between agent and broker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """GetStatus returns current connection status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MT5IngressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=mt5__pb2.AgentMessage.FromString,
                    response_serializer=mt5__pb2.BrokerMessage.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=mt5__pb2.ConnectionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5.v1.MT5IngressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MT5IngressService(object):
    """MT5IngressService is the agent->broker contract.
    The MT5 agent (Python) calls this service to push data to the broker.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mt5.v1.MT5IngressService/Connect',
            mt5__pb2.AgentMessage.SerializeToString,
            mt5__pb2.BrokerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5.v1.MT5IngressService/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            mt5__pb2.ConnectionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
